### ISSUE TITLE
More operations on collections

### ISSUE THREAD

**Issue by lowoli** [nzbasic/Collection-Helper#4]
I like to categorize my beatmaps into different skill sets (e.g. aim, tapping, alt, etc.) and I wanted to generate a collection containing every beatmap I haven't categorized yet. I could do this by taking a collection with all my beatmaps and subtracting the merge of all my skill set collections, but the subtraction step doesn't seem to be doable (if it is, I'm not aware of how) without one of the two following solutions:

Subtraction: Take two collections, A and B, and create a new collection containing beatmaps in A which aren't in B
Negation: Create a new collection from A which contains every beatmap in the user's library that isn't in A
(Sorry if I'm over explaining)

Either of these two functions works for me personally, but I think the program would be better overall if it had both (and XOR too while we're on the topic).

TL;DR please add collection subtraction/negation and maybe even XOR

**Comment by lowoli** [comment]
Oh my fucking god I meant to leave this on Piotrekal's CollectionManager, not here. I can't seem to delete it though. My bad. Ignore everything

**Comment by nzbasic** [comment]
lmao
