### ISSUE TITLE
mania

### ISSUE THREAD

**Issue by japabms** [nzbasic/Collection-Helper#5]
Could you add the keys command to verify osu!mania maps by keymode? like key=7 or keys=7 to show only seven keys maps

**Comment by nzbasic** [comment]
Added keys filter in 1.5.4 (restart client to update), usage is keys=number. It only works for native mania maps. Turns out the circle size is equal to the number of keys in mania, so my bandaid fix was just converting keys=4 into mode=3 cs=4
